# sql_project
# 	Dataset : Online Food Orders

-- creating database 
create database online_food_orders;
use online_food_orders;

-- creating tables 
DROP TABLE IF EXISTS orders;
CREATE TABLE Customers (
	Customer_Id	int ,
	Customer_Name varchar(25) ,	
	City varchar(25) ,
	Signup_Date date 
) ;
DROP TABLE IF EXISTS Orders ;
CREATE TABLE Orders (
	Order_Id	int,
    Customer_Id	int,
    Restaurant_Id	int,
    Order_Date	date,
    Order_Amount	float,
    Payment_Method	varchar(50),
    Order_Status varchar(25)
);
DROP TABLE IF EXISTS Restaurants ;
CREATE TABLE Restaurants(
	Restaurant_Id int,
	Restaurant_Name	varchar(50) ,
    City varchar(50) ,
	Rating float 
) ;
SELECT * FROM Customers;
SELECT * FROM Orders;
SELECT * FROM restaurants;

-- checking null values in Customers table
SELECT * FROM customers
WHERE Customer_Id IS NULL OR
	Customer_Name IS NULL OR
	City IS NULL OR
	Signup_Date ;
    
-- checking null values in Orders table
SELECT * FROM Orders
WHERE Order_Id	IS NULL OR
    Customer_Id	IS NULL OR
    Restaurant_Id IS NULL OR
    Order_Date IS NULL OR
    Order_Amount IS NULL OR
    Payment_Method IS NULL OR
    Order_Status ;
    
-- checking null values in Restaurants table
SELECT * FROM Restaurants 
WHERE Restaurant_Id IS NULL OR
	Restaurant_Name	IS NULL OR 
    City IS NULL OR
	Rating ; 
    
SELECT * FROM Customers;
SELECT * FROM Orders;
SELECT * FROM restaurants;

-- 1.	Display all completed orders along with customer name and restaurant name. 
SELECT C.Customer_Id,  C.customer_name, R.restaurant_name ,O.Order_Status
FROM customers C JOIN orders O 
ON C.Customer_Id = O.Customer_Id
JOIN restaurants R 
ON O.Restaurant_Id = R.Restaurant_Id
WHERE Order_Status = "Completed";

-- 2.	Find the total revenue generated by each restaurant. 
SELECT R.restaurant_name , SUM(Order_Amount) AS Amount
FROM orders O JOIN restaurants R 
ON O.Restaurant_Id= R.Restaurant_Id
GROUP BY R.Restaurant_Name;

-- 3.	Show the total number of orders placed by each customer.
SELECT C.Customer_Id, C.customer_name, COUNT(O.order_id ) AS orders_placed
FROM customers C JOIN orders O 
ON C.customer_id = O.customer_id 
GROUP BY  C.Customer_Id, C.Customer_Name
order by orders_placed ;

-- 4.	Find the average order amount for each city.
SELECT R.city , AVG(Order_Amount) AS Amount
FROM orders O JOIN restaurants R 
ON O.Restaurant_Id= R.Restaurant_Id
GROUP BY R.city;

-- 5.	Categorize orders as Low, Medium, and High based on order amount.
SELECT Order_Amount,
 (  Case 
	WHEN Order_Amount >= 1000 THEN "High"
    WHEN Order_Amount >= 500  THEN "Medium"
    Else "Low"
    END ) AS Amount_Spending
 FROM orders
 Order by Order_Amount ,
	( CASE Amount_Spending
		WHEN "High" THEN 1
		WHEN "Medium" THEN 2
		WHEN "Low" THEN 3
		END ) ;

-- 6.	Display restaurants whose average order value is greater than the overall average order value. 
SELECT R.restaurant_name , COUNT(O.order_id) AS above_avg_orders
FROM restaurants R JOIN orders O 
ON R.Restaurant_Id = O.Restaurant_Id
GROUP BY R.Restaurant_Name
HAVING COUNT(Order_Id ) > 
( 
		SELECT AVG(avg_count) FROM 
		(  SELECT COUNT(order_id) AS avg_count 
		FROM orders
        GROUP BY Restaurant_id
		) temp
);

-- 7.	Find customers who have never placed any orders. 
SELECT C.Customer_Id, C.Customer_Name  
FROM customers C LEFT JOIN orders O 
ON C.Customer_Id= O.Customer_Id 
WHERE O.Order_Status IS NULL;
-- all customers placed orders

-- 8.	Show the top 5 customers based on total spending. 
SELECT C.customer_name , SUM(o.order_amount) AS total_amount 
FROM customers C Join orders O 
ON C.customer_id = O.customer_id
Group by C.Customer_Name
Order by total_amount Desc
Limit 5;

-- 9.	Find the most frequently used payment method. 
SELECT payment_method, COUNT(*) AS repeated_used FROM Orders
GROUP BY payment_method 
ORDER BY repeated_used DESC
LIMIT 1;

-- 10.	Calculate the running total of revenue by order date. 
SELECT Order_Date, daily_revenue ,
SUM(daily_revenue) over(ORDER BY Order_Date) AS running_total
from 
( SELECT order_date, SUM(order_amount) AS daily_revenue
FROM orders
GROUP BY Order_Date
)temp ;

-- 11.	Rank restaurants based on total revenue generated. 
SELECT restaurant_name,
       total_revenue,
       DENSE_RANK() OVER (ORDER BY total_revenue DESC) AS ranks_restaurant
FROM (
    SELECT R.restaurant_name,
           SUM(O.Order_Amount) AS total_revenue
    FROM restaurants R
    JOIN orders O
    ON O.Restaurant_Id = R.Restaurant_Id
    GROUP BY R.restaurant_name
) temp;

-- 12.	Find the second highest order amount from the orders table.
SELECT  MAX(order_amount) AS second_highest_amount FROM orders
WHERE Order_Amount < ( SELECT MAX(Order_Amount) FROM orders );
 
-- 13.	Find customers who placed more orders than the average number of orders per customer. 
SELECT  C.customer_name, count(O.order_id ) AS avg_orders_placed
FROM customers C JOIN orders O 
ON C.customer_id = O.customer_id 
GROUP BY C.Customer_Name
HAVING COUNT(o.order_id) >
( SELECT AVG(Order_count) FROM 
	(
        SELECT COUNT(order_id) AS order_count
        FROM orders
        GROUP BY customer_id
    ) temp
);

-- 14.	Display the top 3 restaurants in each city based on total orders received. 
SELECT *  FROM 
( SELECT R.city, R.restaurant_name,
		 COUNT(O.order_id) AS total_orders,
		 DENSE_RANK() OVER(PARTITION BY R.city ORDER BY COUNT(O.order_id) DESC) AS rnk
		 FROM restaurants R JOIN orders O
         ON R.restaurant_id = O.restaurant_id
         GROUP BY R.city , R.restaurant_name
) temp
WHERE rnk <= 3;

-- 15.	Calculate month-wise revenue and show the previous month revenue.
SELECT month_no, revenue,
       LAG(revenue) OVER(ORDER BY month_no) AS previous_month_revenue
       FROM ( SELECT MONTH(order_date) AS month_no,
			  SUM(order_amount) AS revenue
              FROM orders
              GROUP BY MONTH(order_date)
			) temp;

-- END OF THE PROJECT












